/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLawStatsRouteImport } from './routes/api/public/law-stats'
import { Route as ApiPublicIngestLawRouteImport } from './routes/api/public/ingest-law'
import { Route as ApiPublicArticleRouteImport } from './routes/api/public/article'
import { Route as ApiPublicAnalyzeRouteImport } from './routes/api/public/analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLawStatsRoute = ApiPublicLawStatsRouteImport.update({
  id: '/api/public/law-stats',
  path: '/api/public/law-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLawRoute = ApiPublicIngestLawRouteImport.update({
  id: '/api/public/ingest-law',
  path: '/api/public/ingest-law',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticleRoute = ApiPublicArticleRouteImport.update({
  id: '/api/public/article',
  path: '/api/public/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeRoute = ApiPublicAnalyzeRouteImport.update({
  id: '/api/public/analyze',
  path: '/api/public/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/article': typeof ApiPublicArticleRoute
  '/api/public/ingest-law': typeof ApiPublicIngestLawRoute
  '/api/public/law-stats': typeof ApiPublicLawStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/article': typeof ApiPublicArticleRoute
  '/api/public/ingest-law': typeof ApiPublicIngestLawRoute
  '/api/public/law-stats': typeof ApiPublicLawStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/article': typeof ApiPublicArticleRoute
  '/api/public/ingest-law': typeof ApiPublicIngestLawRoute
  '/api/public/law-stats': typeof ApiPublicLawStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/analyze'
    | '/api/public/article'
    | '/api/public/ingest-law'
    | '/api/public/law-stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/analyze'
    | '/api/public/article'
    | '/api/public/ingest-law'
    | '/api/public/law-stats'
  id:
    | '__root__'
    | '/'
    | '/api/public/analyze'
    | '/api/public/article'
    | '/api/public/ingest-law'
    | '/api/public/law-stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAnalyzeRoute: typeof ApiPublicAnalyzeRoute
  ApiPublicArticleRoute: typeof ApiPublicArticleRoute
  ApiPublicIngestLawRoute: typeof ApiPublicIngestLawRoute
  ApiPublicLawStatsRoute: typeof ApiPublicLawStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/law-stats': {
      id: '/api/public/law-stats'
      path: '/api/public/law-stats'
      fullPath: '/api/public/law-stats'
      preLoaderRoute: typeof ApiPublicLawStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-law': {
      id: '/api/public/ingest-law'
      path: '/api/public/ingest-law'
      fullPath: '/api/public/ingest-law'
      preLoaderRoute: typeof ApiPublicIngestLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article': {
      id: '/api/public/article'
      path: '/api/public/article'
      fullPath: '/api/public/article'
      preLoaderRoute: typeof ApiPublicArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze': {
      id: '/api/public/analyze'
      path: '/api/public/analyze'
      fullPath: '/api/public/analyze'
      preLoaderRoute: typeof ApiPublicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAnalyzeRoute: ApiPublicAnalyzeRoute,
  ApiPublicArticleRoute: ApiPublicArticleRoute,
  ApiPublicIngestLawRoute: ApiPublicIngestLawRoute,
  ApiPublicLawStatsRoute: ApiPublicLawStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
